-- Main Class Of Business
SELECT
    DISTINCT
    contract_object_id = ip.OBJECT_ID,
    name = LTRIM(RTRIM(rd.NAME)),
    code = LTRIM(RTRIM(CAST(rd.CODE AS VARCHAR(15))))
-- INTO #type_of_participation
FROM INSURED_PERIOD AS ip
JOIN BUSINESS AS b
    ON ip.FK_BUSINESS = b.OBJECT_ID
JOIN BUS_STRUCT_REP AS BRT
    ON ip.OBJECT_ID = BRT.FK_INS_PERIOD
JOIN BUS_CLASSIFIC AS bc
    ON bc.OBJECT_ID = BRT.FK_SOC_CLASSIFIC
INNER JOIN CLASSIF_REF_DATA AS c
    ON c.FK_CLASSIFICATION = bc.OBJECT_ID
INNER JOIN REFERENCE_DATA AS rd
    ON c.FRK_REF_DATA = rd.CODE
    AND c.FSK_REF_DATA = rd.SUBCLASS
WHERE BRT.IS_CURRENT_LCP = 'Y'
AND BRT.HIERARCHY_LEVEL = 1
AND BRT.SOC_IS_ACTIVE = 'Y'
AND BRT.SOC_SUBCLASS
BETWEEN 2 AND 5
AND c.FSK_REF_DATA = 19;
--SELECT * FROM ref_data_type