SELECT
    REPORTING_TABLE.FK_INS_PERIOD                    AS contract_object_id,
    REPORTING_TABLE.IDENTIFIER                       AS business_id,
    CAST(REPORTING_TABLE.INSRD_PERIOD_START AS DATE) AS insured_period_from,
    PA.FK_INS_PERIOD                                 AS pa_contract_object_id,
    PA.IDENTIFIER                                    AS pa_business_id,
    CAST(PA.INSRD_PERIOD_START AS DATE)              AS pa_insured_period_from,
    CASE BUS_RETRO.RETROCEDED_VALUE
        WHEN NULL THEN
            CASE BC_SHARE.CUR_SHARE_PCT
                WHEN 0 THEN
                    0
                ELSE
    ((BC_SHARE_PA.CUR_SHARE_PCT / BC_SHARE.CUR_SHARE_PCT) * 100)
            END
        ELSE
            BUS_RETRO.RETROCEDED_VALUE
    END / 100                                        AS retroceded_g__ct,
    PA.FRK_LEVEL_OF_BUS                              AS level_of_business_code,
    BC_SHARE_PA.CUR_SHARE_PCT / 100.0                AS pa_current_share
FROM BC_SHARE             AS BC_SHARE
RIGHT JOIN BUS_STRUCT_REP AS REPORTING_TABLE
    ON REPORTING_TABLE.FK_PC_SHARE = BC_SHARE.OBJECT_ID
LEFT JOIN BUS_RETRO       AS BUS_RETRO
    ON BUS_RETRO.FK_RETRO_IBR = REPORTING_TABLE.FK_PROT_ASS
LEFT JOIN BUS_STRUCT_REP  AS PA
    ON PA.FK_INS_PERIOD = BUS_RETRO.FK_INSURED_PERIOD
    AND PA.IS_CURRENT_LCP = 'Y'
    AND PA.HIERARCHY_LEVEL = 1
LEFT JOIN BC_SHARE        AS BC_SHARE_PA
    ON BC_SHARE_PA.OBJECT_ID = PA.FK_PC_SHARE
WHERE REPORTING_TABLE.HIERARCHY_LEVEL = 1
AND REPORTING_TABLE.SOC_IS_ACTIVE = 'Y'
AND PA.IDENTIFIER IS NOT NULL
AND PA.FRK_LEVEL_OF_BUS IN ( 'OCC', 'ORP' )
AND REPORTING_TABLE.IS_CURRENT_LCP = 'Y'
--AND PA.IDENTIFIER IN ( 'OP531', 'OPPR623' )
--AND PA.INSRD_PERIOD_START = '2021-01-01'

--AND BC_SHARE_PA.CUR_SHARE_PCT	 <> 100.0 
--AND BC_SHARE_PA.CUR_SHARE_PCT	IS NOT null
--AND REPORTING_TABLE.IDENTIFIER = 'ITPR212263'
--AND REPORTING_TABLE.INSRD_PERIOD_START = '2010-01-01'
--AND BC_SHARE_PA.CUR_SHARE_PCT <> 100.0
GROUP BY
    REPORTING_TABLE.FK_INS_PERIOD,
    REPORTING_TABLE.IDENTIFIER,
    CAST(REPORTING_TABLE.INSRD_PERIOD_START AS DATE),
    PA.FK_INS_PERIOD,
    PA.IDENTIFIER,
    CAST(PA.INSRD_PERIOD_START AS DATE),
    CASE BUS_RETRO.RETROCEDED_VALUE
        WHEN NULL THEN
            CASE BC_SHARE.CUR_SHARE_PCT
                WHEN 0 THEN
                    0
                ELSE
    ((BC_SHARE_PA.CUR_SHARE_PCT / BC_SHARE.CUR_SHARE_PCT) * 100)
            END
        ELSE
            BUS_RETRO.RETROCEDED_VALUE
    END,
    BC_SHARE_PA.CUR_SHARE_PCT,
    PA.FRK_LEVEL_OF_BUS;

