SELECT 
	Id					= CAST(Id AS bigint), 
	[Type]				= CAST([Type] AS NVARCHAR(255)),		
	[version]			= CAST([version] AS INT), 
	Name				= CAST(Name AS NVARCHAR(255)),		
	Description			= CAST(Description AS NVARCHAR(255)),		
	Comment				= CAST(Comment AS NVARCHAR(255)),		
	Active				= CAST(Active AS BIT), 
	BriefName			= CAST(BriefName AS NVARCHAR(255)),		
	Iso3166				= CAST(Iso3166 AS NVARCHAR(255)),		
	Town_State_Code		= CAST(Town_State_Code AS NVARCHAR(255)),		
	Town_State_Name		= CAST(Town_State_Name AS NVARCHAR(255)),		
	Zone_County_Code	= CAST(Zone_County_Code AS NVARCHAR(255)),		
	Zone_County_Name	= CAST(Zone_County_Name AS NVARCHAR(255)),		
	SubZone				= CAST(SubZone AS NVARCHAR(255)),		
	LevelId				= CAST(LevelId AS BIGINT), 
	NaturalKey			= CAST(NaturalKey AS NVARCHAR(255)),		
	[Path]				= CAST([Path] AS NVARCHAR(255)),		
	ParentId			= CAST(ParentId AS BIGINT), 
	Classification		= CAST(Classification AS NVARCHAR(255))
FROM [dbo].[Area]